### ISSUE TITLE
Support for XGBoost

### ISSUE THREAD

**Issue by miyurud** [wso2-extensions/siddhi-gpl-execution-pmml#17]
Need to have support for XGBoost algorithm with Siddhi PMML extension.

[1] https://github.com/dmlc/xgboost

**Comment by pcnfernando** [comment]
The extension has been released (v4.0.5) with the support for PMML v4.3 which supports XGBoost.
Included a test specific for a XGBoost.pmml  (predictXGBoostTest)

**Comment by miyurud** [comment]
Thanks Chiran for fixing this issue.
