### ISSUE TITLE
Update JPMML-Evaluator dependency

### ISSUE THREAD

**Issue by vruusmann** [wso2-extensions/siddhi-gpl-execution-pmml#18]
This extension depends on the JPMML-Evaluator library version 1.1.16, which is ~2.5 year old (released in February 2015). It's two development cycles (1.2.X and 1.3.X) behind the current version, and as such doesn't benefit from any improvements and optimizations that have been implemented over the time.

Also, please note that JPMML-Evaluator 1.1.0 and newer are released under Affero GPLv3, which means that the license grant of this extension is invalid.

**Comment by niveathika** [comment]
Hi, 

Thank you for pointing out these issues. 

After review, we have found conflicting license grants for both JPMML-Evaluator and Pmml-Manager dependencies. We are in the process of updating the licenses (https://github.com/wso2-gpl/orbit) and releasing this extension under AGPL license as soon as possible.

Updating JPMML-Evaluator dependency is also being planned for future releases.

Thank You.

**Comment by niveathika** [comment]
The extension has been released (v4.0.2) with the updated AGPLv3 license after the PR merge (https://github.com/wso2-extensions/siddhi-gpl-execution-pmml/pull/20 )
